
# added by travis gem
[ -f /Users/domsmith/.travis/travis.sh ] && source /Users/domsmith/.travis/travis.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
